name: CI-CD_Test

on: 
    push:
        branches: [Action]
    workflow_dispatch:   # <- bisa run manual kapan aja

jobs: 
    run-tests:
        runs-on: ubuntu-latest

        steps: 
            # Checkout Repository
            - name: Checkout repository
              uses: actions/checkout@v3

            # Setup Node.js (untuk newman)
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '18'

            # Install Newman
            - name: Install Newman
              run: npm install -g newman

            # Debug folder untuk cek file
            - name: Debug folder Postman
              run: |
                echo "Isi semua folder:"
                ls -R
                echo "Isi folder 3.Manual_Test_Postman:"
                ls -lah "${GITHUB_WORKSPACE}/3.Manual_Test_Postman" || echo "Folder nggak ada!"

            # Run Postman Collection
            - name: Run Postman Collection
              run: |
                newman run "${GITHUB_WORKSPACE}/3.Manual_Test_Postman/API_postman_collection.json" \
                -e "${GITHUB_WORKSPACE}/3.Manual_Test_Postman/env_postman.json"
